spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sante
    username: sante
    password: santeVie
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create


server:
  port=8080:

